version: '1'

services:

  app:
    container_name: gestion-cuentas
    build: .
    ports:
      - 8880:8880
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: desa
    ports:
      - 3306:3306